"""Build Stage 1 hidden-state VQ artifacts for the selected R6c teacher.

The Joseph Stage 1 package used a windowed VQ-VAE over policy hidden states and
returned three public artifacts:

* train_codes.parquet
* code_summary.csv
* stage1_metrics.csv

This script builds the same handoff shape for the R6c K-window teacher.  It is
deliberately self-contained: it reads the Huawei result zips, replays the saved
policy, extracts policy hidden states, joins them to the rich R6c daily behavior
logs, and fits a windowed VQ-style KMeans codebook.  The K-window env calls the
policy once per macro-step and may emit several daily rows; the policy hidden
state is therefore broadcast to the daily rows generated by that macro-step.
"""

from __future__ import annotations

import argparse
import io
import json
import math
import sys
import tempfile
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml
from sklearn.cluster import KMeans
from sklearn.metrics import normalized_mutual_info_score

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from extract_stage0_1_hidden_state_package import policy_layers  # noqa: E402
from src.ppo.instrumented_ppo import InstrumentedPPO  # noqa: E402
from src.ppo.stage0_1_train import append_eval_info_row  # noqa: E402
from src.ppo.stage0_1_weight_env import load_weight_panel, make_env_from_config  # noqa: E402


DEFAULT_R6C_DIR = (
    ROOT
    / "artifacts"
    / "stage0_1"
    / "R6c_root_K20_stock_K5_PD_mild_slice_group_riskaware_top8_sell12_rotation_internaldays_v1"
)
DEFAULT_OUT_DIR = (
    ROOT
    / "artifacts"
    / "stage1"
    / "R6c_root_K20_stock_K5_PD_mild_slice_group_riskaware_top8_sell12_stage1"
)


@dataclass(frozen=True)
class ExtractedZip:
    zip_path: Path
    config: dict[str, Any]
    metadata: dict[str, Any]
    model_path: Path
    model_ready_path: Path
    fold_name: str


def read_zip_member(zf: zipfile.ZipFile, suffix: str) -> bytes:
    matches = [name for name in zf.namelist() if name.endswith(suffix)]
    if not matches:
        raise FileNotFoundError(f"No zip member ending with {suffix}")
    matches.sort(key=len)
    return zf.read(matches[0])


def read_zip_text(zf: zipfile.ZipFile, suffix: str) -> str:
    return read_zip_member(zf, suffix).decode("utf-8")


def extract_minimal_zip(zip_path: Path, tmp_dir: Path) -> ExtractedZip:
    with zipfile.ZipFile(zip_path) as zf:
        config = yaml.safe_load(read_zip_text(zf, "config.yaml"))
        metadata = json.loads(read_zip_text(zf, "/metadata.json"))
        model_bytes = read_zip_member(zf, "/model.zip")
        model_ready_bytes = read_zip_member(zf, "/model_ready.csv")

    fold = metadata["fold"]["fold"]
    fold_dir = tmp_dir / fold
    fold_dir.mkdir(parents=True, exist_ok=True)
    model_path = fold_dir / "model.zip"
    model_ready_path = fold_dir / "model_ready.csv"
    model_path.write_bytes(model_bytes)
    model_ready_path.write_bytes(model_ready_bytes)
    return ExtractedZip(
        zip_path=zip_path,
        config=config,
        metadata=metadata,
        model_path=model_path,
        model_ready_path=model_ready_path,
        fold_name=fold,
    )


def split_window(metadata: dict[str, Any], split: str) -> tuple[str, str]:
    fold = metadata["fold"]
    if split == "train":
        return fold["train_start"], fold["train_end_inclusive"]
    if split == "validation":
        return fold["validation_start"], fold["validation_end_inclusive"]
    raise ValueError(f"Unsupported split: {split}")


def flatten_array(prefix: str, values: np.ndarray, labels: list[str]) -> dict[str, float]:
    out: dict[str, float] = {}
    arr = np.asarray(values).reshape(-1)
    for i, value in enumerate(arr):
        suffix = labels[i] if i < len(labels) else str(i)
        out[f"{prefix}_{suffix}"] = float(value)
    return out


def replay_split(
    artifact: ExtractedZip,
    *,
    split: str,
    include_observations: bool,
) -> tuple[pd.DataFrame, dict[str, np.ndarray], dict[str, Any]]:
    """Replay a split and return one row per internal trading day."""

    start, end = split_window(artifact.metadata, split)
    panel = load_weight_panel(artifact.model_ready_path, start, end)
    env = make_env_from_config(panel, artifact.config, artifact.metadata["variant"])
    model = InstrumentedPPO.load(
        str(artifact.model_path),
        device="cpu",
        custom_objects={"instrumentation_dir": None},
    )
    model.policy.set_training_mode(False)

    obs, _ = env.reset()
    done = False
    macro_step = 0
    rows: list[dict[str, Any]] = []
    hidden_rows: list[np.ndarray] = []
    value_hidden_rows: list[np.ndarray] = []
    action_rows: list[np.ndarray] = []
    action_param_rows: list[np.ndarray] = []
    obs_rows: list[np.ndarray] = []
    log_prob_rows: list[float] = []
    entropy_rows: list[float] = []
    value_rows: list[float] = []

    while not done:
        layer_out = policy_layers(model.policy, obs)
        action = np.asarray(layer_out["action_mode"], dtype=np.float32)
        obs, reward, terminated, truncated, info = env.step(action)
        done = bool(terminated or truncated)

        daily_steps = info.get("daily_steps")
        if isinstance(daily_steps, list) and daily_steps:
            iterable = list(enumerate(daily_steps))
        else:
            iterable = [(0, info)]

        for daily_idx, daily_info in iterable:
            before = len(rows)
            append_eval_info_row(rows, panel, daily_info, float(daily_info.get("reward", reward)))
            row = rows[-1]
            row["fold"] = artifact.fold_name
            row["split"] = split
            row["source_zip"] = artifact.zip_path.name
            row["macro_step_id"] = macro_step
            row["daily_idx_in_macro_step"] = daily_idx
            row["macro_policy_update_date"] = str(info.get("date", daily_info.get("date", "")))
            if len(rows) != before + 1:
                raise RuntimeError("append_eval_info_row did not append exactly one row")

            hidden_rows.append(np.asarray(layer_out["policy_latent_64"], dtype=np.float32))
            value_hidden_rows.append(np.asarray(layer_out["value_latent"], dtype=np.float32))
            action_rows.append(np.asarray(layer_out["action_mode"], dtype=np.float32))
            action_param_rows.append(np.asarray(layer_out["raw_action_params"], dtype=np.float32))
            log_prob_rows.append(float(layer_out["log_prob_mode"]))
            entropy_rows.append(float(layer_out["entropy"]))
            value_rows.append(float(layer_out["value"]))
            if include_observations:
                obs_rows.append(np.asarray(layer_out["obs"], dtype=np.float32))

        macro_step += 1

    behavior = pd.DataFrame(rows)
    arrays: dict[str, np.ndarray] = {
        "hidden": np.vstack(hidden_rows).astype(np.float32),
        "value_latent": np.vstack(value_hidden_rows).astype(np.float32),
        "action_mode": np.vstack(action_rows).astype(np.float32),
        "raw_action_params": np.vstack(action_param_rows).astype(np.float32),
        "log_prob_mode": np.asarray(log_prob_rows, dtype=np.float32),
        "entropy": np.asarray(entropy_rows, dtype=np.float32),
        "value": np.asarray(value_rows, dtype=np.float32),
    }
    if include_observations:
        arrays["observations"] = np.vstack(obs_rows).astype(np.float32)

    meta = {
        "tickers": list(panel.tickers),
        "feature_columns": list(panel.feature_columns),
        "dates": list(panel.dates),
        "split_start": start,
        "split_end": end,
    }
    return behavior, arrays, meta


def zscore_fit(x: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mean = x.mean(axis=0, keepdims=True)
    std = x.std(axis=0, keepdims=True)
    std = np.where(std < 1e-8, 1.0, std)
    return mean.astype(np.float32), std.astype(np.float32)


def centered_windows(x: np.ndarray, window: int) -> tuple[np.ndarray, np.ndarray]:
    if window % 2 != 1:
        raise ValueError("window_length must be odd")
    pad = window // 2
    n, d = x.shape
    padded = np.pad(x, ((pad, pad), (0, 0)), mode="edge")
    out = np.empty((n, window * d), dtype=np.float32)
    for i in range(n):
        out[i] = padded[i : i + window].reshape(-1)
    valid = np.ones(n, dtype=bool)
    if pad:
        valid[:pad] = False
        valid[-pad:] = False
    return out, valid


def fit_kmeans_codes(
    hidden: np.ndarray,
    *,
    k: int,
    window_length: int,
    seed: int,
) -> dict[str, Any]:
    mean, std = zscore_fit(hidden)
    z = (hidden - mean) / std
    windows, valid = centered_windows(z.astype(np.float32), window_length)
    train_x = windows[valid]
    model = KMeans(n_clusters=k, random_state=seed, n_init=20, max_iter=500)
    model.fit(train_x)
    codes = model.predict(windows).astype(np.int32)
    reconstructed = model.cluster_centers_[model.predict(train_x)]
    mse = float(np.mean((train_x - reconstructed) ** 2))
    var_h = float(np.var(train_x))
    counts = np.bincount(codes[valid], minlength=k).astype(float)
    probs = counts / max(counts.sum(), 1.0)
    nonzero = probs[probs > 0]
    entropy = -float(np.sum(nonzero * np.log(nonzero))) if nonzero.size else 0.0
    perplexity = float(np.exp(entropy))
    return {
        "model": model,
        "codes": codes,
        "valid": valid,
        "mean": mean,
        "std": std,
        "mse": mse,
        "var_h": var_h,
        "recon_over_var": mse / var_h if var_h > 0 else math.nan,
        "counts": counts,
        "utilization": float((counts > 0).sum() / k),
        "perplexity": perplexity,
    }


def apply_existing_codebook(
    hidden: np.ndarray,
    *,
    mean: np.ndarray,
    std: np.ndarray,
    model: KMeans,
    window_length: int,
) -> tuple[np.ndarray, np.ndarray]:
    z = ((hidden - mean) / std).astype(np.float32)
    windows, valid = centered_windows(z, window_length)
    return model.predict(windows).astype(np.int32), valid


def run_lengths(codes: np.ndarray, valid: np.ndarray | None = None) -> list[int]:
    if valid is not None:
        codes = codes[valid]
    if codes.size == 0:
        return []
    runs: list[int] = []
    current = int(codes[0])
    length = 1
    for value in codes[1:]:
        ivalue = int(value)
        if ivalue == current:
            length += 1
        else:
            runs.append(length)
            current = ivalue
            length = 1
    runs.append(length)
    return runs


def summarize_codes(
    frame: pd.DataFrame,
    *,
    code_col: str = "code_id",
    valid_col: str = "valid",
    k: int,
) -> pd.DataFrame:
    df = frame.loc[frame[valid_col]].copy()
    if "net_return" in df.columns:
        return_col = "net_return"
    elif "gross_return" in df.columns:
        return_col = "gross_return"
    else:
        return_col = None

    rows: list[dict[str, Any]] = []
    denom = max(len(df), 1)
    for code in range(k):
        sub = df.loc[df[code_col] == code]
        row = {
            "code_id": code,
            "n": int(len(sub)),
            "freq": float(len(sub) / denom),
            "mean_return": float(pd.to_numeric(sub[return_col], errors="coerce").mean()) if return_col and len(sub) else np.nan,
            "median_return": float(pd.to_numeric(sub[return_col], errors="coerce").median()) if return_col and len(sub) else np.nan,
            "mean_vix": float(pd.to_numeric(sub.get("market_feature_VIX", pd.Series(dtype=float)), errors="coerce").mean()) if len(sub) else np.nan,
            "mean_regime_p1": float(
                pd.to_numeric(sub.get("market_feature_Regime_1_Prob", pd.Series(dtype=float)), errors="coerce").mean()
            )
            if len(sub)
            else np.nan,
        }
        rows.append(row)
    return pd.DataFrame(rows)


def aggregate_behavior_by_code(frame: pd.DataFrame, *, k: int) -> pd.DataFrame:
    useful_patterns = (
        "q_",
        "cash_",
        "risk_stress",
        "recovery_score",
        "confidence_",
        "root_",
        "trade_",
        "turnover",
        "drawdown",
        "concentration",
        "topk_",
        "incremental_topk_",
        "group_",
        "market_feature_",
        "net_return",
        "gross_return",
        "reward",
    )
    numeric_cols = [
        col
        for col in frame.columns
        if col not in {"code_id", "date", "next_date", "fold", "split", "source_zip"}
        and any(col.startswith(pattern) or pattern in col for pattern in useful_patterns)
        and pd.api.types.is_numeric_dtype(frame[col])
    ]
    rows: list[dict[str, Any]] = []
    valid_frame = frame.loc[frame["valid"]].copy()
    for code in range(k):
        sub = valid_frame.loc[valid_frame["code_id"] == code]
        row: dict[str, Any] = {"code_id": code, "n": int(len(sub))}
        for col in numeric_cols:
            values = pd.to_numeric(sub[col], errors="coerce")
            if values.notna().any():
                row[f"mean_{col}"] = float(values.mean())
        rows.append(row)
    return pd.DataFrame(rows)


def select_behavior_columns(frame: pd.DataFrame) -> list[str]:
    exact = {
        "date",
        "next_date",
        "fold",
        "split",
        "source_zip",
        "macro_step_id",
        "daily_idx_in_macro_step",
        "macro_policy_update_date",
        "reward",
        "gross_return",
        "net_return",
        "portfolio_value",
        "turnover_l1",
        "stock_turnover_l1",
        "drawdown",
        "concentration",
        "q_target",
        "cash_target",
        "q_anchor",
        "cash_anchor",
        "q_scheduled",
        "cash_scheduled",
        "q_exec",
        "cash_exec",
        "risk_score",
        "risk_stress",
        "recovery_score",
        "confidence_derisk",
        "confidence_rerisk",
        "delta_q_anchor",
        "delta_q_scheduled",
        "root_anchor_risk_day",
        "root_anchor_cash_day",
        "root_anchor_hold_day",
        "root_scheduled_risk_day",
        "root_scheduled_cash_day",
        "root_scheduled_hold_day",
        "recovery_trigger",
        "risk_break_trigger",
        "window_closed_early",
        "stop_active",
        "suppressed_trade_l1",
        "suppressed_turnover",
        "trade_buy_count",
        "trade_sell_count",
        "trade_hold_count",
        "trade_buy_weight_l1",
        "trade_sell_weight_l1",
        "cash_trade_delta",
        "cash_trade_direction",
        "risky_hhi_target",
        "risky_entropy_target",
        "target_to_executed_l1",
        "anchor_to_schedule_l1",
        "schedule_to_exec_l1",
    }
    prefixes = (
        "market_feature_",
        "topk_",
        "incremental_topk_",
        "group_",
        "trade_direction_",
        "trade_delta_weight_",
        "trade_abs_weight_",
        "executed_weight_",
        "target_weight_",
        "anchor_weight_",
    )
    selected = []
    for col in frame.columns:
        if col in exact or any(col.startswith(prefix) for prefix in prefixes):
            selected.append(col)
    return selected


def primary_rows_from_latest_fold(all_rows: pd.DataFrame, all_arrays: dict[str, np.ndarray]) -> tuple[pd.DataFrame, dict[str, np.ndarray]]:
    """Use fold_2021 train+validation as the main continuous 2010-2021 sequence."""

    mask = all_rows["fold"].eq("fold_2021") & all_rows["split"].isin(["train", "validation"])
    primary = all_rows.loc[mask].copy().reset_index(drop=True)
    idx = np.flatnonzero(mask.to_numpy())
    arrays = {key: value[idx] for key, value in all_arrays.items()}
    primary["date"] = pd.to_datetime(primary["date"]).dt.strftime("%Y-%m-%d")
    primary = primary.sort_values(["date", "split"]).drop_duplicates("date", keep="last").reset_index(drop=True)
    # Reorder arrays after date duplicate handling.
    kept_original = primary.index.to_numpy()
    # The sorted/drop operation reset the index, so recover by matching dates in
    # the original masked order.
    date_to_first_idx = {str(pd.Timestamp(date).date()): i for i, date in enumerate(all_rows.loc[idx, "date"])}
    ordered = np.asarray([date_to_first_idx[date] for date in primary["date"]], dtype=int)
    arrays = {key: value[ordered] for key, value in arrays.items()}
    return primary, arrays


def build_cross_fold_nmi(
    all_rows: pd.DataFrame,
    all_arrays: dict[str, np.ndarray],
    primary_codes: pd.DataFrame,
    *,
    k: int,
    window_length: int,
    seed: int,
) -> float:
    scores: list[float] = []
    primary_map = dict(zip(primary_codes["date"], primary_codes["code_id"]))
    for fold in sorted(all_rows["fold"].dropna().unique()):
        mask = all_rows["fold"].eq(fold) & all_rows["split"].isin(["train", "validation"])
        fold_rows = all_rows.loc[mask].copy().reset_index(drop=True)
        if len(fold_rows) < k + window_length:
            continue
        hidden = all_arrays["hidden"][np.flatnonzero(mask.to_numpy())]
        result = fit_kmeans_codes(hidden, k=k, window_length=window_length, seed=seed)
        dates = pd.to_datetime(fold_rows["date"]).dt.strftime("%Y-%m-%d").to_numpy()
        paired_a: list[int] = []
        paired_b: list[int] = []
        for date, code, valid in zip(dates, result["codes"], result["valid"]):
            if not valid or date not in primary_map:
                continue
            paired_a.append(int(primary_map[date]))
            paired_b.append(int(code))
        if len(set(paired_a)) > 1 and len(set(paired_b)) > 1:
            scores.append(float(normalized_mutual_info_score(paired_a, paired_b)))
    return float(np.mean(scores)) if scores else math.nan


def write_npz_package(
    out_path: Path,
    *,
    primary: pd.DataFrame,
    arrays: dict[str, np.ndarray],
    behavior_columns: list[str],
    tickers: list[str],
    feature_columns: list[str],
) -> None:
    behavior_values = primary[behavior_columns].copy()
    for col in behavior_values.columns:
        if behavior_values[col].dtype == object:
            behavior_values[col] = behavior_values[col].astype(str)
    np.savez_compressed(
        out_path,
        model_id=np.asarray(["R6c_root_K20_stock_K5_PD_mild_slice_group_riskaware_top8_sell12"], dtype="U128"),
        tickers=np.asarray(tickers, dtype="U32"),
        feature_columns=np.asarray(feature_columns, dtype="U128"),
        train_dates=primary["date"].astype(str).to_numpy(),
        train_hidden=arrays["hidden"].astype(np.float32),
        train_policy_latent_final=arrays["hidden"].astype(np.float32),
        train_value_latent=arrays["value_latent"].astype(np.float32),
        train_action_mode=arrays["action_mode"].astype(np.float32),
        train_raw_action_params=arrays["raw_action_params"].astype(np.float32),
        train_logprob=arrays["log_prob_mode"].astype(np.float32),
        train_entropy=arrays["entropy"].astype(np.float32),
        train_value=arrays["value"].astype(np.float32),
        train_code_id=primary["code_id"].to_numpy(dtype=np.int32),
        train_code_valid=primary["valid"].to_numpy(dtype=bool),
        train_net_return=pd.to_numeric(primary.get("net_return"), errors="coerce").to_numpy(dtype=np.float32),
        train_cash_target=pd.to_numeric(primary.get("cash_target"), errors="coerce").to_numpy(dtype=np.float32),
        train_cash_executed=pd.to_numeric(primary.get("cash_exec", primary.get("cash_target")), errors="coerce").to_numpy(dtype=np.float32),
        train_risk_stress=pd.to_numeric(primary.get("risk_stress"), errors="coerce").to_numpy(dtype=np.float32),
        train_recovery_score=pd.to_numeric(primary.get("recovery_score"), errors="coerce").to_numpy(dtype=np.float32),
        train_confidence_derisk=pd.to_numeric(primary.get("confidence_derisk"), errors="coerce").to_numpy(dtype=np.float32),
        train_confidence_rerisk=pd.to_numeric(primary.get("confidence_rerisk"), errors="coerce").to_numpy(dtype=np.float32),
        behavior_columns=np.asarray(behavior_columns, dtype="U128"),
        behavior_values=behavior_values.to_numpy(dtype=object),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--r6c-dir", type=Path, default=DEFAULT_R6C_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--window-length", type=int, default=17)
    parser.add_argument("--selected-k", type=int, default=8)
    parser.add_argument("--candidate-k", type=int, nargs="+", default=[4, 8, 16, 32, 64])
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--include-observations", action="store_true")
    args = parser.parse_args()

    zip_paths = sorted(args.r6c_dir.glob("*.zip"))
    if not zip_paths:
        raise FileNotFoundError(f"No result zips found in {args.r6c_dir}")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "per_fold").mkdir(exist_ok=True)

    all_frames: list[pd.DataFrame] = []
    all_arrays_parts: dict[str, list[np.ndarray]] = {}
    fold_meta: list[dict[str, Any]] = []
    tickers: list[str] = []
    feature_columns: list[str] = []

    with tempfile.TemporaryDirectory(prefix="r6c_stage1_") as tmp_name:
        tmp_dir = Path(tmp_name)
        for zip_path in zip_paths:
            artifact = extract_minimal_zip(zip_path, tmp_dir)
            fold_meta.append({"zip": zip_path.name, "fold": artifact.metadata["fold"], "variant": artifact.metadata["variant"]["name"]})
            for split in ["train", "validation"]:
                print(f"Replaying {artifact.fold_name} {split} from {zip_path.name}", flush=True)
                frame, arrays, meta = replay_split(artifact, split=split, include_observations=args.include_observations)
                tickers = meta["tickers"]
                feature_columns = meta["feature_columns"]
                frame.to_parquet(args.out_dir / "per_fold" / f"{artifact.fold_name}_{split}_behavior.parquet", index=False)
                np.savez_compressed(
                    args.out_dir / "per_fold" / f"{artifact.fold_name}_{split}_hidden.npz",
                    dates=frame["date"].astype(str).to_numpy(),
                    hidden=arrays["hidden"],
                    value_latent=arrays["value_latent"],
                    action_mode=arrays["action_mode"],
                    raw_action_params=arrays["raw_action_params"],
                    log_prob_mode=arrays["log_prob_mode"],
                    entropy=arrays["entropy"],
                    value=arrays["value"],
                )
                all_frames.append(frame)
                for key, value in arrays.items():
                    if key == "observations":
                        continue
                    all_arrays_parts.setdefault(key, []).append(value)

    all_rows = pd.concat(all_frames, ignore_index=True)
    all_arrays = {key: np.vstack(parts) if parts[0].ndim > 1 else np.concatenate(parts) for key, parts in all_arrays_parts.items()}
    all_rows["date"] = pd.to_datetime(all_rows["date"]).dt.strftime("%Y-%m-%d")
    all_rows.to_parquet(args.out_dir / "all_behavior_long.parquet", index=False)

    primary, primary_arrays = primary_rows_from_latest_fold(all_rows, all_arrays)
    metrics_rows: list[dict[str, Any]] = []
    selected_result: dict[str, Any] | None = None
    for k in args.candidate_k:
        result = fit_kmeans_codes(primary_arrays["hidden"], k=k, window_length=args.window_length, seed=args.seed)
        runs = run_lengths(result["codes"], result["valid"])
        cross_nmi = build_cross_fold_nmi(
            all_rows,
            all_arrays,
            pd.DataFrame({"date": primary["date"], "code_id": result["codes"], "valid": result["valid"]}),
            k=k,
            window_length=args.window_length,
            seed=args.seed,
        )
        metrics_rows.append(
            {
                "K": k,
                "best_val_recon": result["mse"],
                "best_epoch": np.nan,
                "utilization": result["utilization"],
                "perplexity": result["perplexity"],
                "recon_mse_normalized": result["mse"],
                "var_h": result["var_h"],
                "recon_over_var": result["recon_over_var"],
                "median_run_length": float(np.median(runs)) if runs else np.nan,
                "cross_fold_nmi": cross_nmi,
                "source": "windowed_kmeans_vq_r6c",
            }
        )
        if k == args.selected_k:
            selected_result = result

    if selected_result is None:
        raise ValueError(f"selected_k={args.selected_k} not included in candidate_k")

    primary = primary.copy()
    primary["code_id"] = selected_result["codes"]
    primary["valid"] = selected_result["valid"]
    train_codes = primary[["date", "code_id", "valid"]].copy()
    train_codes.to_parquet(args.out_dir / "train_codes.parquet", index=False)
    train_codes.to_csv(args.out_dir / "train_codes.csv", index=False)

    code_summary = summarize_codes(primary, k=args.selected_k)
    code_summary.to_csv(args.out_dir / "code_summary.csv", index=False)

    behavior_columns = select_behavior_columns(primary)
    behavior_log = primary[["date", "code_id", "valid"] + [c for c in behavior_columns if c not in {"date"}]].copy()
    behavior_log.to_parquet(args.out_dir / "behavior_log_daily.parquet", index=False)
    behavior_log.to_csv(args.out_dir / "behavior_log_daily.csv", index=False)

    code_behavior_summary = aggregate_behavior_by_code(primary, k=args.selected_k)
    code_behavior_summary.to_csv(args.out_dir / "code_behavior_summary.csv", index=False)

    stage1_metrics = pd.DataFrame(metrics_rows)
    stage1_metrics.to_csv(args.out_dir / "stage1_metrics.csv", index=False)
    selected_metric_row = stage1_metrics.loc[stage1_metrics["K"].eq(args.selected_k)].copy()
    selected_metric_row.to_csv(args.out_dir / "stage1_metrics_selected_k.csv", index=False)

    write_npz_package(
        args.out_dir / "r6c_stage1_hidden_state_package.npz",
        primary=primary,
        arrays=primary_arrays,
        behavior_columns=behavior_columns,
        tickers=tickers,
        feature_columns=feature_columns,
    )

    manifest = {
        "model": "R6c_root_K20_stock_K5_PD_mild_slice_group_riskaware_top8_sell12_rotation_internaldays_v1",
        "source_dir": str(args.r6c_dir),
        "output_dir": str(args.out_dir),
        "primary_sequence": "fold_2021 train+validation daily internal rows, one code per date",
        "hidden_alignment": "Policy hidden state is extracted once per env macro-step and broadcast to daily rows emitted by that macro-step.",
        "window_length": args.window_length,
        "selected_k": args.selected_k,
        "candidate_k": args.candidate_k,
        "folds": fold_meta,
        "outputs": {
            "train_codes": "train_codes.parquet",
            "code_summary": "code_summary.csv",
            "stage1_metrics": "stage1_metrics.csv",
            "behavior_log_daily": "behavior_log_daily.parquet",
            "code_behavior_summary": "code_behavior_summary.csv",
            "hidden_package": "r6c_stage1_hidden_state_package.npz",
        },
    }
    (args.out_dir / "stage1_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    readme = f"""# Stage 1 R6c Hidden-State Codes

Model:
`R6c_root_K20_stock_K5_PD_mild_slice_group_riskaware_top8_sell12_rotation_internaldays_v1`

This package mirrors Joseph's Stage 1 handoff shape:

- `train_codes.parquet`: `date`, `code_id`, `valid`
- `code_summary.csv`: per-code return/VIX/regime summary
- `stage1_metrics.csv`: K sweep metrics with Joseph-compatible columns

Additional files for the more interpretable R6c teacher:

- `behavior_log_daily.parquet`: daily code assignments joined to R6c logs
- `code_behavior_summary.csv`: per-code means for cash/risk/confidence/top-k/group logs
- `r6c_stage1_hidden_state_package.npz`: hidden states, action params, selected behavior arrays

Important alignment detail:
R6c uses K-window execution. One PPO policy call may generate several internal
trading days. The extracted policy hidden state is therefore broadcast to all
daily rows generated by that macro-step. This is intentional: Stage 1 codes
represent the policy state that controlled that K-window segment.

Market context note:
`mean_vix` and `mean_regime_p1` in `code_summary.csv` are computed from the
model-ready normalized features logged by R6c. Use `code_behavior_summary.csv`
and `behavior_log_daily.parquet` for detailed calibrated comparisons across
cash/risk, confidence, group, and Top-K behavior.

Selected K: `{args.selected_k}`
Window length: `{args.window_length}` centered trading days.
Boundary rows with incomplete centered windows are marked `valid == False`.
"""
    (args.out_dir / "README_STAGE1_R6C.md").write_text(readme, encoding="utf-8")
    print(f"Stage 1 R6c package written to {args.out_dir}")


if __name__ == "__main__":
    main()
